tabela_brasileirao = ("Vasco (RJ)", "São Caetano (SP)", "Cruzeiro (MG)", "Grêmio (RS)", "Sport (PE)", "Internacional (RS)", "Palmeiras (SP)", "Paraná (PR)", "Fluminense (RJ)", "Goiás (GO)", "Ponte Preta (SP)", "São Paulo (SP)", "Atlético (PR)", "Bahia (BA)", "Malutrom (PR)", "Remo (PA)", "Guarani (SP)", "Santos (SP)", "Flamengo (RJ)", "Botafogo (RJ)", "Portuguesa (SP)", "Vitória (BA)", "América (MG)", "Atlético (MG)", "Juventude (RS)", "Gama (DF)", "Coritiba (PR)", "Corinthians (SP)", "Santa Cruz (PE)")    

tabela_brasileirao_mod = tuple((indice, valor) for indice, valor in enumerate(tabela_brasileirao, start=1))
print("-"*178)
print("Lista de times do brasileirao: ",tabela_brasileirao_mod)
print("-"*178)
print("Os 5 primeiros sao: ",tabela_brasileirao_mod[:5])
print("-"*178)
print("Os 4 ultimos: ", tabela_brasileirao_mod[-4:])
print("-"*178)
print(f"Time em ordem algabetica: {sorted(tabela_brasileirao)}")
print("-"*178)
print(f"A posicao da Portuguesa (SP): ", tabela_brasileirao.index("Portuguesa (SP)")+1)
print("-"*178)
